/**
 * `npm run fonts`: the committed Noto Serif JP fallback, Google Fonts' variable font (SIL OFL)
 * instanced at 400 and 700 and subset to the site's character set. The face is named as in the
 * product's DEFAULT_FONT_STACK, so it fills in only where no OS Mincho exists.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';

import subsetFont from 'subset-font';

import { writeIfChanged } from '../../scripts/write.ts';
import { collectGlyphs, unicodeRanges } from './glyphs.ts';
import { sitePath } from './root.ts';

const SOURCE = 'https://github.com/google/fonts/raw/main/ofl/notoserifjp/NotoSerifJP%5Bwght%5D.ttf';
const CACHE = sitePath('.cache/NotoSerifJP[wght].ttf');
const WEIGHTS = [400, 700] as const;

/** The variable font, downloaded once into .cache/. */
async function source(): Promise<Buffer> {
  try {
    return await readFile(CACHE);
  } catch {
    // not cached yet
  }
  const res = await fetch(SOURCE);
  if (!res.ok) {
    throw new Error(`fonts: ${SOURCE} → ${String(res.status)}`);
  }
  const ttf = Buffer.from(await res.arrayBuffer());
  await mkdir(sitePath('.cache'), { recursive: true });
  await writeFile(CACHE, ttf);
  return ttf;
}

const chars = await collectGlyphs();
const count = Array.from(chars).length;
const ranges = unicodeRanges(chars);
const ttf = await source();
await mkdir(sitePath('public/fonts'), { recursive: true });
const faces: string[] = [];
for (const wght of WEIGHTS) {
  const woff2 = await subsetFont(ttf, chars, { targetFormat: 'woff2', variationAxes: { wght } });
  const out = sitePath(`public/fonts/NotoSerifJP-${String(wght)}.woff2`);
  await writeFile(out, woff2);
  console.log(`${out}: ${String((await stat(out)).size)} bytes`);
  faces.push(
    '@font-face {\n' +
    "  font-family: 'Noto Serif JP';\n" +
    '  font-style: normal;\n' +
    `  font-weight: ${String(wght)};\n` +
    '  font-display: swap;\n' +
    `  src: url('/fonts/NotoSerifJP-${String(wght)}.woff2') format('woff2');\n` +
    `  unicode-range: ${ranges};\n` +
    '}\n',
  );
}
await writeIfChanged(sitePath('public/fonts/subset.json'), `${JSON.stringify({
  source: SOURCE,
  sourceSha256: createHash('sha256').update(ttf).digest('hex'),
  count,
  chars,
}, null, 1)}\n`);
await writeIfChanged(sitePath('src/styles/fonts.css'), `/* Generated by scripts/fonts.ts — run \`npm run fonts\` after changing the site's text. */\n${faces.join('')}`);
console.log(`${String(count)} characters`);
