/**
 * Codegen for the browser-context programs under `src/client/webview/`. Each module has a TS
 * entry (compiled to a self-executing IIFE by esbuild) and any number of `.css` files; this
 * bundles/reads them into string modules their hosts inline into a `<script>`/`<style>`:
 * the webviews (`book/webviewHtml.ts`, `preview/preview.ts` — a strict CSP forbids loadable
 * scripts) and the compiler's paginated outputs (css.ts `emrProbe()`). Also vendors the
 * `@vscode/codicons` font into `media/codicon/` (served to the webview via `asWebviewUri`).
 *
 * The generated modules are gitignored and regenerated on demand: `npm run gen` (also `prepare`,
 * so a fresh clone self-heals) and every esbuild build regenerate them; watch re-runs on a source
 * change. Nothing here is committed — there is no stale artifact to drift from.
 *
 * The webview TS is a SEPARATE program (DOM lib, no node/vscode — src/client/webview/tsconfig.json). It never
 * enters the host's module graph: the host imports only the string it produces, so the browser code
 * is never bundled as node-target code into `dist/client/extension.js`.
 */
import { copyFile, mkdir, readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import * as esbuild from 'esbuild';

import { writeIfChanged } from './write.ts';

const ROOT = fileURLToPath(new URL('../', import.meta.url));

const HEADER =
  '// GENERATED by scripts/gen-webview.ts — DO NOT EDIT. Run `npm run gen` (a build regenerates it too).\n';

/** One generated module: the browser-JS entry (+ optional CSS), and where they land. */
interface WebviewModule {
  /** Browser TS entry point, bundled to an IIFE string export `jsExport`. */
  readonly entry: string;
  readonly jsExport: string;
  /** CSS files, each inlined verbatim (trimmed) as the string export `cssExport`. */
  readonly css?: readonly { readonly file: string; readonly cssExport: string }[];
  /** The committed-shape `*.generated.ts` this module writes. */
  readonly out: string;
}

const MODULES: readonly WebviewModule[] = [
  {
    entry: join(ROOT, 'src/client/webview/book/main.ts'),
    jsExport: 'BOOKS_JS',
    css: [{ file: join(ROOT, 'src/client/webview/book/styles.css'), cssExport: 'BOOKS_CSS' }],
    out: join(ROOT, 'src/client/book/webviewBundle.generated.ts'),
  },
  {
    entry: join(ROOT, 'src/client/webview/preview/main.ts'),
    jsExport: 'PREVIEW_JS',
    css: [
      { file: join(ROOT, 'src/client/webview/preview/loading.css'), cssExport: 'LOADING_CSS' },
      { file: join(ROOT, 'src/client/webview/preview/widget.css'), cssExport: 'WIDGET_CSS' },
    ],
    out: join(ROOT, 'src/client/preview/webviewBundle.generated.ts'),
  },
  {
    // Compiler payload, not a webview: renderBook/renderPreview inline it, so the generated
    // module lands in src/shared. The SOURCE stays here, inside the one DOM-lib program.
    entry: join(ROOT, 'src/client/webview/probe/emr.ts'),
    jsExport: 'EMR_PROBE_JS',
    out: join(ROOT, 'src/shared/compiler/emrProbe.generated.ts'),
  },
];

const CODICON_SRC = join(ROOT, 'node_modules/@vscode/codicons/dist');
const CODICON_DEST = join(ROOT, 'media/codicon');
const CODICON_FILES = ['codicon.css', 'codicon.ttf'];

/** Bundle one browser entry to a self-executing IIFE string (minified in production). */
async function bundleScript(entry: string, production: boolean): Promise<string> {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    minify: production,
    write: false,
    logLevel: 'warning',
  });
  const [file] = result.outputFiles;
  if (file === undefined) {
    throw new Error(`esbuild produced no output for ${entry}`);
  }
  return file.text;
}

/** Renders one generated module's full text (JS bundle + the verbatim CSS files, as string exports). */
async function renderModule(mod: WebviewModule, production: boolean): Promise<string> {
  const js = await bundleScript(mod.entry, production);
  let cssDecl = '';
  for (const { file, cssExport } of mod.css ?? []) {
    const css = (await readFile(file, 'utf8')).trim();
    cssDecl += `export const ${cssExport} = ${JSON.stringify(css)};\n`;
  }
  return HEADER + cssDecl + `export const ${mod.jsExport} = ${JSON.stringify(js)};\n`;
}

/** Vendor the codicon font + stylesheet into `media/codicon/` (served via asWebviewUri). */
async function copyCodicons(): Promise<void> {
  await mkdir(CODICON_DEST, { recursive: true });
  await Promise.all(
    CODICON_FILES.map((f) => copyFile(join(CODICON_SRC, f), join(CODICON_DEST, f))),
  );
}

/** Every source file whose change should re-trigger codegen (for esbuild watch). */
export async function webviewSourcePaths(): Promise<string[]> {
  const dir = join(ROOT, 'src/client/webview');
  const paths: string[] = [];
  for (const name of await readdir(dir, { recursive: true })) {
    if (name.endsWith('.ts') || name.endsWith('.css')) {
      paths.push(join(dir, name));
    }
  }
  return paths.sort();
}

let inFlight: Promise<boolean> | null = null;

/**
 * Regenerate the browser-program modules + vendor codicons; returns whether any module changed.
 * Coalesces concurrent callers (each generated-module onLoad of one watch rebuild calls this)
 * onto a single run, so no caller's `readFile` can observe a half-written output.
 */
export async function writeWebviewModules(production = false): Promise<boolean> {
  inFlight ??= (async (): Promise<boolean> => {
    try {
      await copyCodicons();
      const results = await Promise.all(
        MODULES.map(async (mod) => writeIfChanged(mod.out, await renderModule(mod, production))),
      );
      return results.some(Boolean);
    } finally {
      inFlight = null;
    }
  })();
  return inFlight;
}

// CLI: `node scripts/gen-webview.ts` (via `npm run gen:webview`). Non-minified — the production
// build re-runs writeWebviewModules(true) up front, so the packaged bundle stays minified.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const production = process.argv.includes('--production');
  writeWebviewModules(production)
    .then((changed) => {
      console.log(changed ? 'regenerated webview modules' : 'webview modules up to date');
    })
    .catch((err: unknown) => {
      console.error('error generating webview modules:', err);
      process.exit(1);
    });
}
